employment_portal/company/urls.py
from django.conf.urls import url
from . import views as core_views

app_name = 'company'
urlpatterns = [
    url(r'^cadmin_landing/', core_views.cadmin_landing, name='cadmin_landing'),
    url(r'^cadmin_edit_profile/', core_views.cadmin_edit_profile, name='cadmin_edit_profile'),
    url(r'^cadmin_add_posting/', core_views.cadmin_add_posting, name='cadmin_add_posting'),
    url(r'^cadmin_add_recruiter/', core_views.cadmin_add_recruiter, name='cadmin_add_recruiter'),
    url(r'^cadmin_edit_posting/', core_views.cadmin_edit_posting, name='cadmin_edit_posting'),
    url(r'^cadmin_edit_recruiter/', core_views.cadmin_edit_recruiter, name='cadmin_edit_recruiter'),
    url(r'^cadmin_view_postings/', core_views.cadmin_view_postings, name='cadmin_view_postings'),
    url(r'^cadmin_view_recruiters/', core_views.cadmin_view_recruiters, name='cadmin_view_recruiters'),
    url(r'^', core_views.cadmin_logout, name='cadmin_logout'),
]

employment_portal/employment_portal/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^user_accounts/', include('user_accounts.urls')),
    url(r'^candidates/', include('candidates.urls')),
    url(r'^company/', include('company.urls')),
    #url(r'^offer_solicit/', include('offer_solicit.urls')),
    #url(r'^postings/', include('postings.urls')),
    url(r'^recruiters/', include('recruiters.urls')),
]

employment_portal/home/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

employment_portal/recruiters/urls.py
from django.conf.urls import url

from . import views as core_views

app_name = 'recruiters'
urlpatterns = [
    url(r'^recruiters_landing/', core_views.recruiters_landing, name='recruiters_landing'),
    url(r'^recruiters_postings/', core_views.recruiters_postings, name='recruiters_postings'),
    url(r'^recruiters_sent_offers/', core_views.recruiters_sent_offers, name='recruiters_sent_offers'),
    url(r'^recruiters_smart_match/(?P<job_id>[0-9]+)/', core_views.recruiters_smart_match, name='recruiters_smart_match'),
    url(r'^recruiter_cand_detail/(?P<cand_id>[0-9]+)/(?P<job_id>[0-9]+)/', core_views.recruiter_cand_detail, name='recruiter_cand_detail'),
    url(r'^recruiters_view_post/', core_views.recruiters_view_post, name='recruiters_view_post'),
    url(r'^recruiters_view_solicitations/', core_views.recruiters_view_solicitations, name='recruiters_view_solicitations'),
    url(r'^', core_views.recruiter_logout, name='recruiter_logout'),
]

employment_portal/user_accounts/urls.py
from django.conf.urls import url

from . import views as core_views

app_name = 'user_accounts'
urlpatterns = [
    url(r'^candidatesignup/', core_views.candidatesignup, name='candidatesignup'),
    url(r'^companysignup/', core_views.companysignup, name='companysignup'),
    url(r'^candidatelogin/', core_views.candidatelogin, name='candidatelogin'),
    url(r'^companylogin/', core_views.companylogin, name='companylogin'),
    url(r'^recruiter_login/', core_views.recruiter_login, name='recruiter_login'),
]

employment_portal/templates/cadmin_add_posting.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Add Posting</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="GeneralStyle.css" rel="stylesheet">
  </head>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{%url 'company:cadmin_landing'%}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Add Posting</li>
  </ol>
</nav>
  <body class="bg-light">

    <div class="container">
      <div class="py-5 text-center">
        <h2 class='display-2'>Add Job Posting</h2>
          <p class='text-muted'>Your chances of finding a candidate are best if you don't repeat skills!</p>
      </div>
        

      <div class="row">
        <div class="col-xl">
            {% block content %}
            <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            
        <button class="btn btn-lg btn-primary btn-block mb-4" type="submit">Save</button>
        {% endblock %}
        </div>
      </div>
        </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../../../assets/js/vendor/popper.min.js"></script>
    <script src="../../../../dist/js/bootstrap.min.js"></script>
    <script src="../../../../assets/js/vendor/holder.min.js"></script>
    <script>
      // Example starter JavaScript for disabling form submissions if there are invalid fields
      (function() {
        'use strict';

        window.addEventListener('load', function() {
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var forms = document.getElementsByClassName('needs-validation');

          // Loop over them and prevent submission
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
    </script>
  </body>
</html>




<!--
      <div class="row">
        <div class="col-xl">
          <h4 class="mb-3">Add Post</h4>
            
            <div class="mb-5">
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">Job Title</span>
                </div>
                <input type="text" class="form-control" id="username" placeholder="Cool Job Title" required>
                <div class="invalid-feedback" style="width: 100%;">
                  Your Job Title is required.
                </div>
              </div>
                
                <div class="form-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Job Description</span>
                </div>
                <textarea class="form-control" rows="5" id="comment"></textarea>
            </div>
            </div>
            <div class="form-group">
            <div class="input-group-prepend">
                    <span class="input-group-text">Assigned Recruiter</span>
                </div>
            <select class="form-control" id="exampleFormControlSelect1">
        <option>Recruiter A</option>
        <option>Recruiter B</option>
        <option>Recruiter C</option>
        <option>Recruiter D</option>
        <option>Recruiter E</option>
        </select>
            </div>
            <hr>
        <div class="form-group">
            <div class="input-group-prepend">
                    <span class="input-group-text">Skill 1</span>
                </div>
            <select class="form-control" id="exampleFormControlSelect1">
        <option>Skill A</option>
        <option>Skill B</option>
        <option>Skill C</option>
        <option>Skill D</option>
        <option>Skill E</option>
        </select>
            </div>
        <div class="form-group">
            <div class="input-group-prepend">
                    <span class="input-group-text">Skill 2</span>
                </div>
            <select class="form-control" id="exampleFormControlSelect1">
        <option>Skill A</option>
        <option>Skill B</option>
        <option>Skill C</option>
        <option>Skill D</option>
        <option>Skill E</option>
        </select>
            </div><div class="form-group">
            <div class="input-group-prepend">
                    <span class="input-group-text">Skill 3</span>
                </div>
            <select class="form-control" id="exampleFormControlSelect1">
        <option>Skill A</option>
        <option>Skill B</option>
        <option>Skill C</option>
        <option>Skill D</option>
        <option>Skill E</option>
        </select>
            </div><div class="form-group">
            <div class="input-group-prepend">
                    <span class="input-group-text">Skill 4</span>
                </div>
            <select class="form-control" id="exampleFormControlSelect1">
        <option>Skill A</option>
        <option>Skill B</option>
        <option>Skill C</option>
        <option>Skill D</option>
        <option>Skill E</option>
        </select>
            </div><div class="form-group">
            <div class="input-group-prepend">
                    <span class="input-group-text">Skill 5</span>
                </div>
            <select class="form-control" id="exampleFormControlSelect1">
        <option>Skill A</option>
        <option>Skill B</option>
        <option>Skill C</option>
        <option>Skill D</option>
        <option>Skill E</option>
        </select>
            </div>
            
            
            
            
            
        <a href="{% url 'company:cadmin_view_postings' %}" class="btn-lg btn-primary">Create</a>
        </div>
      </div>
-->

employment_portal/templates/cadmin_login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="GeneralStyle.css" rel="stylesheet">
  </head>

  <body class="text-center">
    <div class='container'>
    {% block content %}
    <h1 class='display-1 mt-5'>Company Log In</h1>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-lg btn-primary btn-block mt-4" type="submit">Log In</button>
        <br>
        <a class="text-muted" href="{% url 'user_accounts:companysignup' %}">Don't have account? Click Here</a>
    </form>
    {% endblock %}
    </div>
  </body>
</html>

employment_portal/templates/cadmin_signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Account</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
{% block content %}
  <h1>Company Sign up</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
  </form>
{% endblock %}
</body>
</html>

employment_portal/templates/cadmin_view_postings.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>View All Postings</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="GeneralStyle.css" rel="stylesheet">
  </head>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'company:cadmin_landing' %}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">View Postings</li>
  </ol>
</nav>
  <body class="bg-light">

    <div class="container">
      <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
        <h1 class='display-4'>View Postings</h1>
      </div>
        

    <ul class="list-group mr-5 ml-5">
        {%for posting in posting_list%}
        <li class="list-group-item mb-2"><div class="media">
            <div class="media-body">
                <label class="text-muted">Job Title</label>
                <h4 class="mt-0 mb-1">{{posting.job_title}}</h4>
                <label class="text-muted">Job Description</label>
                    <p>{{posting.Job_Description}}</p>
                <label class="text-muted">Skills</label>
                <ol class="list-inline">
                    <li class="list-inline-item">
                        {{posting.job_skills_1}}
                    </li>
                    <li class="list-inline-item">
                        {{posting.job_skills_2}}
                    </li>
                    <li class="list-inline-item">
                        {{posting.job_skills_3}}
                    </li>
                    <li class="list-inline-item">
                        {{posting.job_skills_4}}
                    </li>
                    <li class="list-inline-item">
                        {{posting.job_skills_5}}
                    </li>
                    <li class="list-inline-item">
                        {{posting.job_skills_6}}
                    </li>
                    <li class="list-inline-item">
                        {{posting.job_skills_7}}
                    </li>
                    <li class="list-inline-item">
                        {{posting.job_skills_8}}
                    </li>
                    <li class="list-inline-item">
                        {{posting.job_skills_9}}
                    </li>
                    <li class="list-inline-item">
                        {{posting.job_skills_10}}
                    </li>
                </ol>
                {{posting.recruiter}}
            </div>
            
            </div>
        </li>
        
        {%endfor%}
    </ul>

        
      <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">&copy; 2017-2018 Company Name</p>
        <ul class="list-inline">
          <li class="list-inline-item"><a href="#">Privacy</a></li>
          <li class="list-inline-item"><a href="#">Terms</a></li>
          <li class="list-inline-item"><a href="#">Support</a></li>
        </ul>
      </footer>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../../../assets/js/vendor/popper.min.js"></script>
    <script src="../../../../dist/js/bootstrap.min.js"></script>
    <script src="../../../../assets/js/vendor/holder.min.js"></script>
    <script>
      // Example starter JavaScript for disabling form submissions if there are invalid fields
      (function() {
        'use strict';

        window.addEventListener('load', function() {
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var forms = document.getElementsByClassName('needs-validation');

          // Loop over them and prevent submission
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
    </script>
  </body>
</html>

employment_portal/templates/candidate_login_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Success</title>
</head>
<body>
<h1>Success!</h1>
</body>
</html>

employment_portal/templates/company_login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
  </head>

  <body class="text-center">
    <form class="form-signin">
      <h1 class="h3 mb-3 font-weight-normal">Candidate Log In</h1>
      <label for="inputEmail" class="sr-only">Username</label>
      <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <a href="company_admin_landing.html" class="btn btn-lg btn-primary btn-block" type="submit">Sign in</a>
        <br>
        <br>

        <a href="create_admin_account.html">Don't have account? Click Here</a>
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
  </body>
</html>

employment_portal/templates/recruiters_cand_detail.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>View Candidate</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="GeneralStyle.css" rel="stylesheet">
  </head>
    <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'recruiters:recruiters_landing' %}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">View Candidate</li>
  </ol>
</nav>
  <body class="bg-light">

    <div class="container">
      <div class="py-5 text-center">

        <h1 class='display-1'>View Candidate</h1>
      </div>
        

    <ul class="list-group mr-5 ml-5">
        <li class="list-group-item mb-2"><div class="media">
            <div class="media-body">
                <label class="text-muted">User</label>
                <h4 class="mt-0 mb-1">{{cand.user}}</h4>
                <label class="text-muted">Bio</label>
                    <p>{{cand.bio}}</p>
                <label class="text-muted">Skills</label>
                <ol class="list-inline">
                    <li class="list-inline-item">
                        {{cand.skills_choices_1}}
                    </li>
                    <li class="list-inline-item">
                        {{cand.skills_choices_2}}
                    </li>
                    <li class="list-inline-item">
                        {{cand.skills_choices_3}}
                    </li>
                    <li class="list-inline-item">
                       {{cand.skills_choices_4}}
                    </li>
                    <li class="list-inline-item">
                        {{cand.skills_choices_5}}
                    </li>
                    <li class="list-inline-item">
                        {{cand.skills_choices_6}}
                    </li>
                    <li class="list-inline-item">
                        {{cand.skills_choices_7}}
                    </li>
                    <li class="list-inline-item">
                        {{cand.skills_choices_8}}
                    </li>
                    <li class="list-inline-item">
                        {{cand.skills_choices_9}}
                    </li>
                    <li class="list-inline-item">
                       {{cand.skills_choices_10}}
                    </li>
                </ol>
                <label class='text-muted mt-2'>Job</label>
                <p>{{job.job_title}}</p>
            </div>
            <form method="post">
            {% csrf_token %}
            {{form.as_p}}

            <button class="btn btn btn-outline-primary" type="submit">Send Offer</button>

            </form>

            </div>
        </li>
    </ul>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../../../assets/js/vendor/popper.min.js"></script>
    <script src="../../../../dist/js/bootstrap.min.js"></script>
    <script src="../../../../assets/js/vendor/holder.min.js"></script>
    <script>
      // Example starter JavaScript for disabling form submissions if there are invalid fields
      (function() {
        'use strict';

        window.addEventListener('load', function() {
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var forms = document.getElementsByClassName('needs-validation');

          // Loop over them and prevent submission
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
    </script>
  </body>
</html>

employment_portal/templates/recruiters_view_post.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Example Post -> Recruiter</title>

    <!-- Bootstrap core CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="GeneralStyle.css" rel="stylesheet">
  </head>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'recruiters:recruiters_landing' %}">Home</a></li><li class="breadcrumb-item"><a href="{%url 'recruiters:recruiters_postings'%}">My Postings</a></li>
    <li class="breadcrumb-item active" aria-current="page">View Post</li>
  </ol>
</nav>
  <body class="bg-light">

    <div class="container">
      <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
        <h2>Example Post -> Recruiter</h2>
      </div>

      <div class="row">
        <div class="card w-100 h-100">
            <div class="display-1 ml-3">Job Title</div>
            <hr>
            <label class="text-muted ml-3">Job Description</label>
            <blockquote class="blockquote">
                <p class="ml-3 mr-3">
                    “Sonic get up”
                    “No”
                    “What do you mean no have you’ve forgotten that you’re parents are away? That you currently have a whole kingdom waiting for you to control them?” Shadow says as he stands at the edge of sonic’s bed staring impatiently at sonic hidden under piles of cover.
                    “No, I did not forget. How could I forget something so important?”
                    “Then why aren’t you ready?”
                    Shadow watch as the piles of covers slowly rising and Sonic head emerge. He pays close attention to every detail of him from his dark blue fur and emerald eyes. But his admiration also causes him to notice his mishaps such as his baggy eyes, slow movements, and messy bed head hair.
                    “You look like a mess. Clearly not the look of a king” Shadow states placing a hand on his hip.
                    “I guess it’s a good thing I’m not the king then,” Sonic says as he slowly drags himself into the bathroom.
                    Shadow walks towards the bathroom door and leans up on the wall “What were you even doing all night?”
                    “You see I was playing this video game and it kinda kept me playing till like 4:00 in the morning,” Sonic says with excitement but can hear Shadow sigh from the other side of the door. As result, the eager in his voice lessen “I’d tried to quit but I was so close to leveling up so close to getting that last boost of experience.”
                    “I wonder about you sometimes”
                    “You say that as if I act this way around everyone else”
                </p>
            </blockquote>
            <hr>
            <label class="text-muted ml-2">Location</label>
            <h3 class="ml-3">New Donk City</h3>
            <hr>
            <label class="ml-2 text-muted">Desired Skills</label>
            <ol class="list-inline ml-3">
                    <li class="list-inline-item">
                        Skill 1
                    </li>
                    <li class="list-inline-item">
                        Skill 2
                    </li>
                    <li class="list-inline-item">
                        Skill 3
                    </li>
                    <li class="list-inline-item">
                        Skill 4
                    </li>
                    <li class="list-inline-item">
                        Skill 5
                    </li>
                    <li class="list-inline-item">
                        Skill 1
                    </li>
                    <li class="list-inline-item">
                        Skill 2
                    </li>
                    <li class="list-inline-item">
                        Skill 3
                    </li>
                    <li class="list-inline-item">
                        Skill 4
                    </li>
                    <li class="list-inline-item">
                        Skill 5
                    </li>
                </ol>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../../../assets/js/vendor/popper.min.js"></script>
    <script src="../../../../dist/js/bootstrap.min.js"></script>
    <script src="../../../../assets/js/vendor/holder.min.js"></script>
    <script>
      // Example starter JavaScript for disabling form submissions if there are invalid fields
      (function() {
        'use strict';

        window.addEventListener('load', function() {
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var forms = document.getElementsByClassName('needs-validation');

          // Loop over them and prevent submission
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
    </script>
  </body>
</html>

employment_portal/templates/test_cadmin_edit_posting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>